---
title: "Mcap_CD"
author: "Shayle Matsuda"
date: "12/5/2020"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits = 5)              # Modify global options - set sig figs to 5 digits

```

## Mcap CD growth experiment: Buoyant Weight and qPCR
 
#Buoyant WEIGHT
```{r}
#rm(list=ls()) # removes all prior objects
library(tidyverse)
library("car") #levenes test
library("ggplot2") #plotting
library("plotrix") #plotting
require("gridExtra") #Arrange Plots for output
require("utils")
library(lubridate)

#load metadata
geno.frag<-read.csv("UROP_metadata_colony.csv")
  geno.frag$genotype<-as.factor(as.character(geno.frag$genotype))
  geno.frag$frag.id<-as.factor(as.character(geno.frag$frag.id))

#load shade levels
shade.levels<-read.csv("shade.levels.csv")
  shade.levels$frag.id<-as.factor(as.character(shade.levels$frag.id))
  shade.levels$treatment<-as.factor(as.character(shade.levels$treatment))
  shade.levels$light.level<-as.factor((shade.levels$light.level))
  shade.levels<-unique(shade.levels) #remove dups

  # geno_fragid<-geno.frag$frag.id               #Check for missing data
  # shade.levels_fragid<-shade.levels$frag.id
  #diffs<-as.data.frame(setdiff( geno_fragid, shade.levels_fragid))
  #metadata<-merge(shade.levels,geno.frag, by.x="frag.id",no.dups=T)

#add in depth data
geno.depth <- read.csv("UROP_geno_Depth.csv")
geno.depth$genotype <- as.factor(as.character(geno.depth$genotype))
  # meta_genoID<-metadata$genotype        ##### Check for missing data
  # depth_genoID<-geno.depth$genotype
  #diffs<-as.data.frame(setdiff(meta_genoID, depth_genoID)) # no depth data for 912, 916, 909, 911, 910, 922, 920
  #metadata<-merge(metadata,geno.depth, by.x="genotype")

# add tank meta
tank <- read.csv("UROP_frag_tank.csv")
tank$frag.id <- as.factor(as.character(tank$frag.id))

metadata <- full_join(shade.levels, geno.frag)
metadata <- full_join(metadata, tank)
metadata <- full_join(metadata, geno.depth)
metadata <- as_tibble(metadata)

metadata$depth.m<-as.character(metadata$depth.m) #below wouldn't run with depth as numeric, need to flag or remove in downstream, but I dont think we even need it. 

metadata<-dplyr::select(metadata, -c("treatment","tratment", "depth.m")) # cut cols here bc not running in tidyverse below for some unknown reason...

# metadata <- metadata %>% 
#   #select(metadata,-c(-treatment, -tratment,-depth)) %>% #added depth to this bc of NA so can't do much with it anyway 20220713 Also this line doesn't run
#   mutate(depth.m = replace_na(depth.m, "unknown")) %>%
#   drop_na(light.level)
```
BW: original code HP

```{r}
BW.data.T0 <-read.csv('Buoyant_weight/UROP_BW_T0_20171029.csv') 
BW.data.T1 <-read.csv('Buoyant_weight/UROP_BW_T1_20171129.csv') 
BW.data.T2 <-read.csv('Buoyant_weight/UROP_BW_T2_20180108.csv')
BW.data <- rbind(BW.data.T0, BW.data.T1, BW.data.T2) #combine

BW.data<-merge(BW.data, metadata, by.x= "frag.id") 

  BW_fragid<-BW.data$frag.id
  meta_fragid<-metadata$frag.id
  setdiff(BW_fragid, meta_fragid) #check what we lose, 142 144  73 283 217  cannot find genotype info in MO notes


BW.data$frag.id<-as.factor(as.character(BW.data$frag.id))
BW.data$temp.c<-as.numeric(BW.data$temp.c)
BW.data$time.point<-as.factor(as.character(BW.data$time.point))

BW <- BW.data$mass.g
Temp <- BW.data$temp.C 


#HP
# load data 
CalData<-read.csv('Buoyant_weight/Bouyant_weight_calibration_curve.csv', header=T, sep=",")
#Data with Standard weights in grams in deionized water, saltwater, and the temp that they were measured at

#plot relationship between temp and Standard in fresh and salt water
plot(CalData$Temp, CalData$StandardSalt, col = 'red', ylab = 'Salt Weight (g)', xlab = 'Temp C')
par(new=TRUE)
plot(CalData$Temp, CalData$StandardFresh, col = 'blue',xaxt="n",yaxt="n",xlab="",ylab="")
axis(4)
mtext("'Fresh Weight (g)'",side=4,line=3)
legend("topleft",col=c("red","blue"),lty=1,legend=c("Salt","Fresh"), bty = "n")

#linear regression between temp and Standard
#Salt water standard measures
StandardSaltModel <- lm(CalData$StandardSalt~CalData$Temp)
summary(StandardSaltModel)
summary(StandardSaltModel)$r.squared
StandardSaltModel$coef

#Fresh water standard measures
StandardFreshModel <- lm(CalData$StandardFresh~CalData$Temp)
summary(StandardFreshModel)
summary(StandardFreshModel)$r.squared
StandardFreshModel$coef

BW <- BW.data$mass.g
Temp <- BW.data$temp.c 

BWCalc_Mcap <- function(StandardAir= 39.092, Temp, BW, CoralDensity = 2.03){
  #Parameters---------------------------------------------------------------
  # StandardAir is the weight of the Standard in air (Default set at 39.092 grams weighed on balance)
  # Temp is the temperature of the water during the coral measurement
  # BW is the buoywant weight of the coral
  # CoralDensity <- 2.03 #g cm-3, set aragonite density for Montipora from literature 
  #Montipora Arag = 2.03 g cm-3 average from table 2 in Anthony 2003 Functional Ecology 17:246-259
  

 #Calculation------------------------------------------------------------
  #Step 1: correct the Standard weights for temperature
  # StandardFresh is the weight of the Standard in  fresh water at temp x
  # StandardSalt is the weight of the Standard in salt water at temp x
  
  # This is based on a calibration curve for Standards weighed in fresh and salt water at many temps
StandardFresh <- StandardFreshModel$coef[-1]*Temp + StandardFreshModel$coef[1] 
StandardSalt <- StandardSaltModel$coef[-1]*Temp + StandardSaltModel$coef[1] 
  
  # Step 2: Use weight in air and freshwater of the  Standard to calculate
  # the density of the Standard (Davies eq. 4)
FreshDensity <- 1 #Fresh water has a density of 1 g/cm3
StandardDensity <- FreshDensity/(1-(StandardFresh/StandardAir)) 
  
  # Step 3: Calculate the density of seawater using the density of the Standard
  # (Spencer Davies eq. 3)
SWDensity <- StandardDensity*(1-(StandardSalt/StandardAir))
  
  # Step 4: Calculate the dry weight of the coral (Davies eq. 1)
CoralWeight <- BW/(1-(SWDensity/CoralDensity))
  
  return(CoralWeight) #returns coral dry weights in g
}
   
BW.data$Dry.Weigh.g <- BWCalc_Mcap(BW=BW, Temp=Temp) #use function to calculate dry weight
hist(BW.data$Dry.Weigh.g) #not normal
 #BW.data$Dry.Weigh.g_log<-log10(BW.data$Dry.Weigh.g+1)
 #hist(BW.data$Dry.Weigh.g_log) #better
#boxplot(BW.data$Dry.Weigh.g_log) #examine data

# Entering the tidyverse!!!
BW.data <- tibble(BW.data)


# BW.data <- BW.data %>%                        ### not running here so redid in dplyr below
#   select(-mass.g, -temp.c, -notes, -date) 

BW.data<-dplyr::select(BW.data, -c("mass.g","temp.c", "date")) # cut cols here bc not running in tidyverse below for some unknown reason...

```

# qPCR
```{r}
# Read in and tidy processed qPCR data
qpcr <- read_csv("qPCR/qpcr_processed.csv")

qpcr <- qpcr %>%
  dplyr::select(frag.id, time, propD, dom = Dom, mix = Mix) %>%
  mutate(time.point = if_else(time == "Time1", "T0", "T2"),
         frag.id = factor(frag.id)) %>%
  dplyr::select(-time)

# Join qPCR data with BW data
df <- full_join(BW.data, qpcr)
# frags with qPCR data but no BW data or metadata
df %>% filter(is.na(Dry.Weigh.g)) %>% print(n = nrow(.))

# Delete genotype 874 (only 1 frag measured once)
df <- df %>% filter(!genotype == 874 | is.na(genotype))

# Samples with qPCR data but NO BW data --- n=38 (these were frags that died before experiment)
missing_bw <- anti_join(qpcr, BW.data)

# Samples with BW data but NO qPCR data at T0 --- n=43 (these were likely failed qPCRs)
missing_qpcr <- anti_join(BW.data, qpcr) %>%
   filter(time.point == "T0")
#inner_join(missing_qpcr, df)
#df %>% filter(is.na(propD), time.point == "T0")

# Remove all samples with no BW data
df <- df %>%
  filter(!is.na(Dry.Weigh.g))
```

# Fill in missing symbiont data
```{r}
# Sometimes missing symbiont data for frags where qPCR failed -- assign dominant symbiont based on other frags of same geno. First -- check whether any genotypes showed variation in dominant symbiont across frags?
df %>%
  group_by(genotype) %>%
  drop_na(dom) %>%
  dplyr::summarize(sym = paste0(unique(dom), collapse = ",")) %>%
  filter(nchar(sym) > 1)

# Genotype 864 = frags 20, 21. -- each amped once as C and once as D
# frag20 T2 had poor amplification (throw away) -- T0 showed D. 
# frag21 T0 had "A" and "B" run with diff. dom syms... which is right? Use D bc frag20 had D?  or throw away?
# 864 screening biopsy was 90% D
# could switch this colony to all D....

df %>%
  dplyr::filter(genotype == "864")  %>%
  arrange(frag.id, time.point) %>%
  print(n = nrow(.))

# Genotype 867B = frags 47, 48, 49, 50.
# 47=C@T2 ----healthy at T2
# 48=D@T0 ----dead3 by T2
# 49=C@T2 ----dead2 by T2
# 50=D@T0 ----dead5 by T2
# screening biopsy for '867' was D... but was this same colony as 867B?
# If going with T0 data, could label this as a D colony, but weird that T2 samples were both C....shuffling?
# Call this a D colony, but if outlier/weird, probly throw away...
### this 867B at T2 high light had  the highest  growth rate of  all "D" colonies...since  this is an outlier, best to filter out this data point. it probably really was C, and was tagged as wrong genotype. 

# Genotype 868 = frags 109, 110, 111, 112
# all have pretty even mixtures but all C-dom except 112@T0 was D-dom.... but only 58% D. qPCR data looks good.
# ...MIXED
# label this a D for now... D could be defined as morethan background levels of D  / including these mixed colonies

# Genotype 880 = frag 24 only. 90%D@T0, 53%C@T2.....
# ...MIXED

# Genotype 912 = frags 51, 52, 53, 64
# 53 and 64 are 98% D.
# 51 is 100%D@T0, and 100%C@T2.... qPCR data better for the C sample than the D sample...
# no colony screening sample for this genotype
# could label as D colony

# Genotype 922 = frags 70, 84, 85, 86
# 70 is 98%D@T0, 100%C@T2.
# 85 is 96%D@T2
# no colony screening sample

# Going to label all these genotypes as D's for now
genos <- c("864", "867B", "868", "880", "912", "922")
df <- df %>%
  mutate(dom = if_else(genotype %in% genos, "D", dom))

# Are any genotypes entirely missing symbiont data?
df %>%
  group_by(genotype) %>%
  summarize(missingdom = !any(!is.na(dom))) %>%
  filter(missingdom)  
# Yes, genotype 894 has only one fragment (265), and it has no qPCR data.
# Parent colony screening biopsy for 894 was C, so going to label this as C (Mariah's notes also say frag 265 was setup as a brown C colony).
df <- df %>%
  mutate(dom = if_else(genotype == "894", "C", dom))


df <- df %>%
  group_by(genotype) %>%
  mutate(dom = replace_na(dom, unique(dom[!is.na(dom)]))) %>%
  ungroup()

```

# mortality (Percent scores)
```{r}

mort<-read_csv("partialMortality.csv")
mort$frag.id <- as.factor(as.character(mort$frag.id))

mort <- as_tibble(mort)
mort<-drop_na(mort)
mort2<-pivot_wider(mort, names_from = time.point, values_from = percent.mort, )

# Remove frags FROM MORT with high partial mortality at start of experiment: 2, 8, 32, 97, 144, 196, 235and 276
mort2<-mort2 %>%
  filter(!frag.id==2) %>%
  filter(!frag.id==8)%>%
  filter(!frag.id==32)%>%
    filter(!frag.id==97)%>%
    filter(!frag.id==1144)%>%
    filter(!frag.id==196)%>%
    filter(!frag.id==235)%>%
    filter(!frag.id==276)

# Remove frags FROM DF with high partial mortality at start of experiment: 2, 8, 32, 97, 144, 196, 235and 276
df<-df %>%
  filter(!frag.id==2) %>%
  filter(!frag.id==8)%>%
  filter(!frag.id==32)%>%
    filter(!frag.id==97)%>%
    filter(!frag.id==1144)%>%
    filter(!frag.id==196)%>%
    filter(!frag.id==235)%>%
    filter(!frag.id==276)

# change missing T1 mort scores to the score at T2 to be conservative
# ******* Decide if we want to put this back in ********* removed 20220725

# mort2<-mort2 %>%
#   mutate(T1 = case_when(
#     is.na(T1) & T2 == 100 ~ 100,
#     is.na(T1) & T2 == 95 ~ 95,
#     is.na(T1) & T2 == 40 ~ 40,
#     is.na(T1) & T2 == 25 ~ 25,
#     is.na(T1) & T2 == 30 ~ 30,
#     is.na(T1) & T2 == 0 ~ 0,
#     TRUE ~ T1
#   ))

# change missing T2 mort scores to the score at T1 ONLY for 100% mortality
mort2<-mort2 %>%
  mutate(T2 = case_when(
    is.na(T2) & T1 == 100 ~ 100,
    TRUE ~ T2
  ))

mort2<-pivot_longer(mort2, cols = c(T0,T1, T2), names_to = "time.point", values_to = "mortality")

df <- full_join(df, mort2) # we are missing some values. 
# df <- df %>%   # removed 20220725 re-scored mort photos at T0
  # mutate(mortality = if_else(time.point == "T0", 0, mortality)) # mortality at T0 is 0

#remove frags with only T0
df<-df %>%
  filter(!frag.id==25)%>%
    filter(!frag.id==286)


#to edit metadata below, all must go back to characters or numeric....i dont make the rules
df$light.level<-as.character(df$light.level)
df$genotype<-as.character(df$genotype)
df$dom<-as.character(df$dom)
df$big.tank<-as.numeric(df$big.tank)
df$tank<-as.numeric(df$tank)
df$days<-as.numeric(df$days)

df %>% filter(is.na(dom)) #what frags do not have dom symb data: 134, 135, 137, 195
# remove them and then add them back in in a few lines
df<-df %>% filter(!is.na(dom))

# if missing T0 data add back in with metadata
# add meta to T0s without it
 #If days has NA, change to dates based on condition of time.point (T1 or T2)


##### not running so doing by hand below
# df<-df %>%
#   mutate(genotype = case_when(
#     is.na(genotype) & frag.id == "134" & time.point=="T0" ~ "878",
#     is.na(genotype) & frag.id == "135" & time.point=="T0" ~ "878",
#     is.na(genotype) & frag.id == "137" & time.point=="T0" ~ "878",
#     is.na(genotype) & frag.id == "195" & time.point=="T0" ~ "858",
#     TRUE ~ genotype))%>%
#       mutate(light.level = case_when(
#     is.na(light.level) & frag.id == "134" & time.point=="T0" ~ "Natural",
#     is.na(light.level) & frag.id == "135" & time.point=="T0" ~ "Low Shade",
#     is.na(light.level) & frag.id == "137" & time.point=="T0" ~ "High Shade",
#     is.na(light.level) & frag.id == "195" & time.point=="T0" ~ "Low Shade",
#     TRUE ~ light.level)) %>%
#    
#    mutate(big.tank = case_when(
#     is.na(big.tank) & frag.id == 134 & time.point=="T0" ~ "16",
#     is.na(big.tank) & frag.id == 135 & time.point=="T0" ~ "13",
#     is.na(big.tank) & frag.id == 137 & time.point=="T0" ~ "17",
#     is.na(big.tank) & frag.id == 195 & time.point=="T0" ~ "13",
#     TRUE ~ big.tank))%>%
#    mutate(tank = case_when(
#     is.na(tank) & frag.id == 134 & time.point=="T0" ~ "9",
#     is.na(tank) & frag.id == 135 & time.point=="T0" ~ "2",
#     is.na(tank) & frag.id == 137 & time.point=="T0" ~ "26",
#     is.na(tank) & frag.id == 195 & time.point=="T0" ~ "2",
#     TRUE ~ tank))%>%
#    mutate(dom = case_when(
#     is.na(dom) & frag.id == 134 & time.point=="T0" ~ "D",
#     is.na(dom) & frag.id == 135 & time.point=="T0" ~ "D",
#     is.na(dom) & frag.id == 137 & time.point=="T0" ~ "D",
#     is.na(dom) & frag.id == 195 & time.point=="T0" ~ "C",
#     TRUE ~ dom))

#If days has NA, change to dates based on condition of time.point (T1 or T2)
df<-
  df %>%
  mutate(days = case_when(
    is.na(days) & time.point == "T0" ~ 0,
    is.na(days) & time.point == "T2" ~ 60,
    is.na(days) & time.point == "T1" ~ 31,
    TRUE ~ days
  ))


#add rows for T0 if not already included
 df<-df %>%
   add_row(frag.id="134", days=0, time.point="T0", light.level="Natural", genotype="878", big.tank=16, tank=9, dom ="D", mortality=NA)%>%
    add_row(frag.id="135", days=0, time.point="T0", light.level="Low Shade", genotype="878", big.tank=13, tank=9, dom ="D", mortality=NA)%>%
    add_row(frag.id="137", days=0, time.point="T0", light.level="High Shade", genotype="878", big.tank=17, tank=26,  dom ="D", mortality=NA)%>%
    add_row(frag.id="195", days=0, time.point="T0", light.level="Low Shade", genotype="858", big.tank=13, tank=2, dom ="C", mortality=0)

# Frags missing mortality data? yes some, but they are missing values
df %>%
  group_by(frag.id) %>%
  filter(any(is.na(mortality))) %>%
  arrange(frag.id, time.point)
```

```{r}
# Final check for duplicates
df %>%
  count(frag.id, time.point) %>%
  arrange(-n)

df %>%
  filter(frag.id == 21)
# frag 21 at T0 was qPCR'd twice, once showing C and once D -- above, we decided other evidence showed this is a D colony, so we are dropping the C observation
df <- df %>%
  filter(!(frag.id == 21 & time.point == "T0" & propD == 0))
```

```{r}
# Fill in missing metadata for a couple of frags at  T2
df  <- df %>% 
  group_by(frag.id) %>%
  fill(genotype, light.level, big.tank, tank, dom) %>%
  ungroup()

```
Filter frags if symb ID ambiguous
```{r}
# Filter out a few fragments where symbiont identity is ambiguous, e.g., 867B and 922 where the colony was categorized as D based on the majority of frags from that colony, but individual fragments weree 100%C
mislabeled_D <- df %>%
  filter(dom == "D", propD < 0.5)

df <- df %>%
  anti_join(mislabeled_D)

```

# Save cleaned dataset to file
```{r}
write_csv(df, "all_data_cleaned.csv")
```

