---
title: "analysis.Rmd"
output: html_document
editor_options: 
  chunk_output_type: console
---

This is the data analysis script for the manuscript "Symbiont-mediated tradeoffs between growth and heat tolerance are modulated by light and temperature in the coral Montipora capitata" authored by Shayle Matsuda, Mariah Opalek, Raphael Ritson-Williams, Ruth Gates, Ross Cunning.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggpubr)
library(lme4)
library(ggplot2)
library(emmeans)
library(broom.mixed)
library(lubridate)
library(lmerTest)
library(cowplot)
library(EnvStats)
library(tidyverse)

options(digits = 5)              # Modify global options - set sig figs to 5 digits

# Create custom ggplot theme
theme_custom <- function() {
  theme_bw(base_size = 10, base_family = "Arial") %+replace%
    theme(
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), 
      panel.background = element_blank(),
      panel.border = element_rect(color = "black", fill = NA),
      legend.background = element_rect(fill = NA, colour = NA)
    )
}
```

# Load in data
```{r}
# Load buoyant weight and tissue loss data
df <- read_csv("data/processed/all_data_cleaned.csv") %>% 
  mutate(across(.cols = c(time.point, genotype, tank, dom, mix,frag.id, tank, big.tank, light.level), as.factor)) %>%
  mutate(light.level = factor(light.level, levels = c("Natural", "Low Shade", "Medium Shade", "High Shade"))) %>%
  drop_na(light.level)

# Load light data
dli <- read_csv("data/processed/dli.csv") %>%
   dplyr::rename(time.point = timepoint)  %>%
   mutate(light.level = case_when(Shade == "1_cloth" ~ "Natural",
                                  Shade == "2_cloth" ~ "Low Shade",
                                  Shade == "3_cloth" ~ "Medium Shade",
                                  Shade == "4_cloth" ~ "High Shade")) %>%
   dplyr::select(light.level, time.point, dli = avg_dli)
```

# Partial tissue loss
```{r}
df.mort <- df %>%    # make a copy
  left_join(dli)     # join with light data

# Plot individual tissue loss to look at mort/time
ggplot(df.mort, aes(x = days, y = mortality, color = dom, group = frag.id)) +  
  facet_wrap(~light.level) + 
  geom_line()

# Summary stats
df.mort %>% 
  group_by(dli, dom) %>%
  summarise(mean = median(mortality, na.rm = T),
            iqr = paste0(quantile(mortality, probs = c(0.25, 0.75), na.rm = T), collapse = "-"))

# arcsinsqrt transform and get T2 only
df.mort.T2 <- filter(df.mort, time.point == "T2") %>% mutate(asin = asin(sqrt(mortality/100)))

df.mort.T2 %>% 
  group_by(dli, dom) %>%
  summarise(med = median(mortality, na.rm = TRUE),
            p25 = quantile(mortality, 0.25, na.rm = TRUE),
            p75 = quantile(mortality, 0.75, na.rm = TRUE))

df.mort.T2 %>%  #n of corals in mortality dataset by treatment
  group_by(dli, dom) %>%
  count(dli, dom)

# Table 2: Fit lmer ####
mod2 <- lmer(asin ~ dli * dom + (1|tank) + (1|genotype), data = df.mort.T2)
summary(mod2)  # interaction is sig. with lmer on asinsqrt transformed data
hist(residuals(mod2))

# Table S4:  model outputs for lmer dom symbiont* dli ####
emm2 <- emmeans(mod2, ~ dom*dli, at = list(dli = sort(unique(df.mort.T2$dli))))
rbind(contrast(emm2, method = "pairwise", by = c("dli")), adjust = "fdr")

# Get model outputs for lmer by dom symbiont only
emm2 <- emmeans(mod2, ~ dom)
rbind(contrast(emm2, method = "pairwise"), adjust = "fdr")

# reorder factors
df.mort.T2$light.level <- factor(df.mort.T2$light.level, levels = c("High Shade", "Medium Shade", "Low Shade","Natural"))
df.mort.T2<-df.mort.T2[!is.na(df.mort.T2$mortality),]#remove NAs
#create partial mortality groups
df.mort.T2 <- df.mort.T2 %>%
  mutate(mortcat = case_when(mortality == 0 ~ "0",
                             mortality > 0 & mortality < 50 ~ "1-50",
                             mortality >= 50 ~ "50+"))
# Figure 1  ####
fig1<-ggplot(df.mort.T2, aes(x = light.level, fill = mortcat)) +
  scale_fill_manual(values=c('#2A788EFF','#22A884FF', '#7AD151FF'))+
  facet_wrap(~dom) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  geom_bar(position = "fill");fig1

#ggsave(fig1, filename = "output/figure1.pdf", width = 84, height = 84, units= "mm")
```
# Growth
```{r}
# Plot buoyant weight data for each frag
ggplot(df, aes(x = days, y = Dry.Weigh.g, color = dom, group = frag.id)) +
  facet_wrap(~light.level) + 
  geom_line()

# Calculate growth rates
gr <- df %>% # make a copy
  dplyr::select(-c("days","notes","mix", "propD","mortality"))   #remove cols not needed

gr <- gr %>%
  pivot_wider(names_from  = time.point,
              values_from = Dry.Weigh.g) %>%
 # Calculate percent change per day during each time interval
  mutate(grT1 = (T1 - T0)* 1000/T0/31,
         grT2 = (T2 - T1)* 1000/T1/39) %>%
  dplyr::select(-T0, -T1, -T2, T1 = grT1, T2 = grT2) %>%
  pivot_longer(cols = c(T1, T2), names_to = "time.point", values_to = "growth.rate") %>%
  drop_na(growth.rate)

##############################################

# Add mean daily light integrals for light treatment categories
gr <- gr %>%
   full_join(dli)

gr$light.level<-as.factor(gr$light.level)

# Plot growth rates by predictors
ggplot(gr, aes(x = light.level, y = growth.rate)) +
  geom_jitter() +
  facet_grid(time.point ~ dom)

# Fit model to find outliers based on growth rate residuals
grmod <- lmer(growth.rate ~ dom * light.level * time.point + (1|genotype) + (1|frag.id) + (1|tank), data = gr)
grres <- augment(grmod)
ggplot(grres, aes(x = light.level, y = growth.rate)) +
  geom_jitter(aes(color = .cooksd < 0.1)) +
  facet_grid(time.point ~ dom)

# Filter out observations with cooks distance > 0.1
grres.f <- grres %>% filter(.cooksd < 0.1) %>%
  left_join(gr)
nrow(grres) - nrow(grres.f)   # Filtered out 6 observations

##############################################

# Summary stats
grres.f %>%
  group_by(light.level, time.point) %>%
  summarise(meangr = mean(growth.rate))

grres.f %>%
  group_by(light.level, time.point, dom) %>%
  summarise(meangr = mean(growth.rate))

# # Table 3 ####
#Run stats
mod <- lmer(growth.rate ~ dom * dli * time.point + (1|genotype/frag.id) + (1|tank), data = grres.f)
anova(mod)
aug<-augment(mod)
ggplot(aug, aes(x=factor(dli), y=.cooksd))+
  geom_boxplot()+
  facet_grid(~time.point)

# Table S6: Get model outputs ####
emm <- emmeans(mod, ~ dom*dli|time.point, at = list(dli = sort(unique(gr$dli))))
# pairwise comparisons -- only the dli:timepoint combos that actually appear in the data
rbind(contrast(emm, method = "pairwise", by = c("dli", "time.point"))[c(2,4,6,8,9,11,13,15)], adjust = "fdr")

emm <- emmeans(mod, ~ dom|time.point, at = list(dli = sort(unique(gr$dli))))
rbind(contrast(emm, method = "pairwise", by = c( "time.point")), adjust = "fdr")

# Get fitted values to plot
pred <- tidyr::expand(grres.f, dom, time.point, dli = seq(0.331, 4.13, len = 101))
pred$fit <- predict(mod, pred, re.form = NA)
bootfit <- bootMer(mod, nsim = 999, FUN = function(x) predict(x, pred, re.form = NA))
pred$lci <- apply(bootfit$t, 2, quantile, 0.05)
pred$uci <- apply(bootfit$t, 2, quantile, 0.95)

# Figure 2 ####
grplot <- ggplot(grres.f, aes(x = dli, y = growth.rate, color = dom, fill = dom)) +
  facet_wrap(~time.point) +
  geom_violin(aes(group = interaction(dom, dli)), scale = "width", width = 0.3, alpha = 0.5) +
  geom_line(data = pred, aes(y = fit)) +
  geom_ribbon(data = pred, aes(y = fit, ymin = lci, ymax = uci), alpha = 0.2, lwd = 0) +
  scale_color_manual(values=c("deepskyblue3", "chocolate3"), name = NULL) +
  scale_fill_manual(values=c("deepskyblue3", "chocolate3"), name = NULL) +
  theme_custom() +
  theme(legend.position = c(0.05, 0.85)) +
  xlab(expression(Daily~light~integral~(mol~m^-2~d^-1)))+
  ylab(expression(Growth~rate~(mg~g^-1~d^-1)));grplot

# Make temperature plot
tempdat <- read_csv("data/processed/temperature.csv") %>%
  mutate(time.point = if_else(datetime < "2017-11-29", "T1", "T2"))
medtemp <- tempdat %>% group_by(time.point) %>% summarise(med = median(temp, na.rm = T))
tempplot <- ggplot(data=tempdat, aes(x=datetime, y=temp)) +
  geom_smooth(color = "black", show.legend = F, method = "gam", formula = y ~ s(x, bs = "bs")) +
  coord_cartesian(ylim = c(23, 27.2)) +
  theme_custom() +
  labs(x = "", y = "Temp. (°C)");tempplot

t1tempplot <- tempplot %+% filter(tempdat, time.point == "T1") +
  geom_hline(data = filter(medtemp, time.point == "T1"), aes(yintercept = med), linetype = 2) +
  scale_x_datetime(breaks = as_datetime(c("2017-10-29", "2017-11-29")), date_labels = "%e-%b") +
  theme(axis.text.x = element_text(hjust = c(0, 1)),
        axis.title.y = element_text(size = 7))
t2tempplot <- tempplot %+% filter(tempdat, time.point == "T2") +
  geom_hline(data = filter(medtemp, time.point == "T2"), aes(yintercept = med), linetype = 2) +
  scale_x_datetime(breaks = as_datetime(c("2017-11-29", "2018-01-07")), date_labels = "%e-%b") +
  theme(axis.text.y = element_blank(), axis.title.y = element_blank(), axis.ticks.y = element_blank(),
        axis.text.x = element_text(hjust = c(0, 1)),
        plot.margin = margin(l = 0, r = 10, t = 5, b = 5))

# Make figure with insets
fig2 <- ggdraw(grplot) +
  draw_plot(t1tempplot, 0.19, 0.6, 0.32, 0.3) +
  draw_plot(t2tempplot, 0.83, 0.6, 0.3, 0.3, hjust = .94); fig2

#ggsave(fig2, filename = "output/figure2.png", width = 174, height = 90, units = "mm")
```

#qPCR distribution
```{r}
#make boxplot df.mort.T2
qPCR.df <- df %>% # make a copy
  dplyr::select(-c("days","notes","mix", "mortality")) 
qPCR.df<-na.omit(qPCR.df)

p <- ggplot(qPCR.df, aes(x=dom, y=propD)) + 
  geom_boxplot();p

# Figure S4 ####
p1<- ggviolin(qPCR.df, x = "dom", y = "propD",
   add = "boxplot", fill = "dom");p1

#ggsave(p1, filename = "output/figure_qPCR.pdf", width = 174, height = 90, units = "mm")

# calculate median % C/D in C- and D-dom genotypes
qPCR.df.2<-qPCR.df #make a copy
qPCR.df.2<-select(qPCR.df.2, c('frag.id','propD', 'dom'))
percentD<-aggregate(qPCR.df.2$propD, list(qPCR.df.2$frag.id,qPCR.df.2$dom), FUN=mean) 
#C
Cdom<-subset(percentD, Group.2=="C")
  #Cdom.nodom<-subset(Cdom, x>0)
#D
Ddom<-subset(percentD, Group.2=="D")
Ddom$percentC<-1-Ddom$x
  #Ddom.nodom<-subset(Cdom, x>0)

summarise(Cdom, median = median(x))
summarise(Ddom, median = median(percentC))
```